name: bottom_cupertino_tabbar
description: "BottomCupertinoTabbar is a customizable, Cupertino-style Flutter widget for bottom navigation with support for individual navigation stacks per tab."
version: 1.0.4
homepage: https://github.com/iJack93/bottom_cupertino_tabbar

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.1
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - test/assets/bottom/
